name: tests
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - python: 2.7
                      env: TOXENV=py27
                    - python: 3.9
                      env: TOXENV=pep8
                    - python: 3.9
                      env: TOXENV=docs
                    - python: 3.5
                      env: TOXENV=py35
                    - python: 3.6
                      env: TOXENV=py36
                    - python: 3.7
                      env: TOXENV=py37
                    - python: 3.8
                      env: TOXENV=py38
                    - python: 3.9
                      env: TOXENV=py39
                    - python: pypy-3.8
                      env: TOXENV=pypy3
        name: ${{ matrix.env }} on Python ${{ matrix.python }}
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: ${{ matrix.python }}
        - run: pip install tox
        - run: tox
          env:
              TOXENV: ${{ matrix.toxenv }}
