name: tests
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - python: 2.7
                      env: TOXENV=py27
                      arch: amd64
                    - python: 2.7
                      env: TOXENV=pep8
                      arch: amd64
                    - python: 2.7
                      env: TOXENV=docs
                      arch: amd64
                    - python: 3.5
                      env: TOXENV=py35
                      arch: amd64
                    - python: 3.6
                      env: TOXENV=py36
                      arch: amd64
                    - python: 3.7
                      env: TOXENV=py37
                      arch: amd64
                    - python: 3.8
                      env: TOXENV=py38
                      arch: amd64
                    - python: pypy
                      env: TOXENV=pypy
                      arch: amd64
                    - python: pypy3
                      env: TOXENV=pypy3
                      arch: amd64
                    - python: 2.7
                      env: TOXENV=py27
                      arch: ppc64le
                    - python: 2.7
                      env: TOXENV=pep8
                      arch: ppc64le
                    - python: 2.7
                      env: TOXENV=docs
                      arch: ppc64le
                    - python: 3.5
                      env: TOXENV=py35
                      arch: ppc64le
                    - python: 3.6
                      env: TOXENV=py36
                      arch: ppc64le
                    - python: 3.7
                      env: TOXENV=py37
                      arch: ppc64le
                    - python: 3.8
                      env: TOXENV=py38
                      arch: ppc64le
        name: ${{ matrix.env }} on Python ${{ matrix.python }}/${{ matrix.arch}}
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
              python-version: ${{ matrix.python }}
              architecture: ${{ matrix.arch }}
        - run: pip install tox
        - run: tox
          env:
              TOXENV: ${{ matrix.toxenv }}
